version: "3.3"

services:
  redis:
    image: redis:alpine
    container_name: ss_redis
    expose:
      - 6379
    networks:
      localnet:
  web:
    build: .
    container_name: ss_web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "80:8000"
    env_file:
      - ./.env
    networks:
      localnet:
  queue:
    build: .
    container_name: ss_django
    command: bash -c "python manage.py rqworker default --url redis://redis:6379"
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      localnet:

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24