# Generated by Django 4.0.4 on 2022-06-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_alter_binary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='User',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
