# Generated by Django 4.0.4 on 2023-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_event_features_alter_event_ip_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('Major', 'Major'), ('Starter', 'Starter')], default='Major', max_length=20),
        ),
    ]
